###
GET http://localhost HTTP/1.1

###
GET http://localhost/seeder.php HTTP/1.1

###
GET http://localhost/transfer.php HTTP/1.1

###
GET http://localhost/test.php HTTP/1.1

###
GET http://localhost/index.php HTTP/1.1

###
GET http://localhost/async.php HTTP/1.1



